; Scope compiler runtime image assembled at the CP/M load origin.
%INCLUDE "core.asm"
%INCLUDE "managed.asm"
%INCLUDE "../page.asm"
%INCLUDE "primitives.asm"
%INCLUDE "../pair-management.asm"
%INCLUDE "../pairs.asm"
%INCLUDE "roots.asm"
%INCLUDE "data.asm"
%INCLUDE "float.asm"
%INCLUDE "output.asm"
%INCLUDE "slabs.asm"
%INCLUDE "../../../runtime/binary16.asm"
%INCLUDE "../../../runtime/numeric.asm"
