; Length-prefixed operator names.  Keeping these strings beside the parser
; makes the accepted surface obvious without adding a keyword table to output.
K_DEFINE:      DB 6,"define"
K_IF:       DB 2,"if"
K_BEGIN:    DB 5,"begin"
K_LET:      DB 3,"let"
K_LETSEQ:  DB 4,"let*"
K_LETREC: DB 6,"letrec"
K_COND:   DB 4,"cond"
K_ELSE:   DB 4,"else"
K_WHEN:   DB 4,"when"
K_UNLESS: DB 6,"unless"
K_CASE:   DB 4,"case"
K_AND:      DB 3,"and"
K_OR:       DB 2,"or"
K_LAMBDA:    DB 6,"lambda"
K_SET:     DB 4,"set!"
M_OK:    DB "COMPILED",13,10,"$"
M_ERROR:   DB "COMPILE ERROR",13,10,"$"
M_CAP:   DB "CAP",13,10,"$"
M_UNSUP:   DB "UNSUP",13,10,"$"
M_OUTPUT:   DB "OUTPUT ERROR",13,10,"$"
M_EXPECT:   DB "EXPECT",13,10,"$"
M_LETREC:   DB "LETREC",13,10,"$"
M_APPLY:    DB "APPLY",13,10,"$"
M_DEST:    DB "DEST",13,10,"$"
M_DUP:   DB "DUP",13,10,"$"
M_END:     DB "END",13,10,"$"
M_OP:     DB "OP",13,10,"$"
M_DEF:     DB "DEF",13,10,"$"
M_DEFNAM:    DB "DEFNAME",13,10,"$"
M_INCL:   DB "INCLUDE ERROR",13,10,"$"
M_SOURCE:   DB "SOURCE ERROR",13,10,"$"
M_MEMORY:   DB "INSUFFICIENT MEMORY",13,10,"$"
K_QUOTE:    DB 5,"quote"
K_CALLEC:    DB 7,"call/ec"
; Predefined procedures: length, compiler kind and spelling for GLB_PRIM.
NAME_TAB:   DB 1,1,"+"
            DB 1,2,"-"
            DB 1,3,"*"
            DB 1,32,"/"
            DB 5,4,"zero?"
            DB 4,5,"cons"
            DB 3,6,"car"
            DB 3,7,"cdr"
            DB 5,8,"pair?"
            DB 5,9,"null?"
            DB 4,10,"list"
            DB 3,11,"eq?"
            DB 5,12,"write"
            DB 7,13,"display"
            DB 7,14,"newline"
            DB 10,30,"write-char"
            DB 9,31,"read-char"
            DB 8,15,"quotient"
            DB 9,16,"remainder"
            DB 1,17,"="
            DB 1,18,"<"
            DB 1,19,">"
            DB 2,20,"<="
            DB 2,21,">="
            DB 3,22,"not"
            DB 7,23,"number?"
            DB 8,24,"boolean?"
            DB 7,25,"symbol?"
            DB 10,26,"procedure?"
            DB 7,27,"string?"
            DB 5,28,"char?"
            DB 13,33,"string-length"
            DB 10,34,"string-ref"
            DB 13,35,"char->integer"
            DB 13,36,"integer->char"
            DB 6,37,"string"
            DB 11,38,"string-copy"
            DB 13,39,"string-append"
            DB 11,29,"eof-object?"
            DB 7,40,"vector?"
            DB 11,41,"make-vector"
            DB 6,42,"vector"
            DB 13,43,"vector-length"
            DB 10,44,"vector-ref"
            DB 11,45,"vector-set!"
            DB 5,46,"apply"
            DB 4,54,"read"
            DB 18,47,"current-input-port"
            DB 19,48,"current-output-port"
            DB 18,49,"current-error-port"
            DB 5,50,"port?"
            DB 11,51,"input-port?"
            DB 12,52,"output-port?"
            DB 10,53,"close-port"
            DB 15,56,"open-input-file"
            DB 16,57,"open-output-file"
            DB 22,58,"open-input-binary-file"
            DB 23,59,"open-output-binary-file"
            DB 8,61,"set-car!"
            DB 8,62,"set-cdr!"
            DB 6,63,"equal?"
            DB 4,11,"eqv?"
            DB 6,64,"char=?"
            DB 6,65,"char<?"
            DB 6,66,"char>?"
            DB 7,67,"char<=?"
            DB 7,68,"char>=?"
            DB 8,69,"string=?"
            DB 8,70,"string<?"
            DB 8,71,"string>?"
            DB 9,72,"string<=?"
            DB 9,73,"string>=?"
            DB 14,74,"symbol->string"
            DB 14,75,"string->symbol"
            DB 14,76,"number->string"
            DB 6,77,"modulo"
            DB 3,78,"abs"
            DB 6,79,"length"
            DB 7,80,"reverse"
            DB 6,81,"append"
            DB 9,82,"list-tail"
            DB 8,83,"list-ref"
            DB 4,84,"memq"
            DB 4,85,"assq"
            DB 6,86,"member"
            DB 5,87,"assoc"
            DB 5,88,"list?"
            DB 11,89,"char-upcase"
            DB 13,90,"char-downcase"
            DB 16,91,"char-alphabetic?"
            DB 13,92,"char-numeric?"
            DB 16,93,"char-whitespace?"
            DB 9,94,"substring"
