; Length-prefixed operator names.  Keeping these strings beside the parser
; makes the accepted surface obvious without adding a keyword table to output.
SCDEF:      DB 6,"define"
SCIF:       DB 2,"if"
SCBEGIN:    DB 5,"begin"
SCLET:      DB 3,"let"
SCLETST:  DB 4,"let*"
SCLETREC: DB 6,"letrec"
SCCOND:   DB 4,"cond"
SCELSE:   DB 4,"else"
SCAND:      DB 3,"and"
SCOR:       DB 2,"or"
SCLAMBK:    DB 6,"lambda"
SCSETK:     DB 4,"set!"
SCZEROK:    DB 5,"zero?"
SCPADD:     DB 1,"+"
SCPMIN:     DB 1,"-"
SCPMUL:     DB 1,"*"
SCOKTXT:    DB "COMPILED",13,10,"$"
SCERRTXT:   DB "COMPILE ERROR",13,10,"$"
SCCAPTXT:   DB "CAP",13,10,"$"
SCSYNTXT:   DB "SYN",13,10,"$"
SCUNSTXT:   DB "UNSUP",13,10,"$"
SCOUTTXT:   DB "OUTPUT ERROR",13,10,"$"
SCEXPTXT:   DB "EXPECT",13,10,"$"
SCEXTXT:    DB "EXPR",13,10,"$"
SCRECTXT:   DB "LETREC",13,10,"$"
SCAPTXT:    DB "APPLY",13,10,"$"
SCDESTT:    DB "DEST",13,10,"$"
SCDUPTXT:   DB "DUP",13,10,"$"
SCENDT:     DB "END",13,10,"$"
SCOPRT:     DB "OP",13,10,"$"
SCDEFT:     DB "DEF",13,10,"$"
SCDEFNT:    DB "DEFNAME",13,10,"$"
SCMEMTXT:   DB "INSUFFICIENT MEMORY",13,10,"$"
SCQUOTE:    DB 5,"quote"
SCCALEC:    DB 7,"call/ec"
SCNPLUS:    DB 1,"+"
SCNSUB:     DB 1,"-"
SCNMUL:     DB 1,"*"
SCNDIV:     DB 1,"/"
SCNZERO:    DB 5,"zero?"
SCNCONS:    DB 4,"cons"
SCNCAR:     DB 3,"car"
SCNCDR:     DB 3,"cdr"
SCNPAIR:    DB 5,"pair?"
SCNNULL:    DB 5,"null?"
SCNLIST:    DB 4,"list"
SCNEQ:      DB 3,"eq?"
SCNWRIT:    DB 5,"write"
SCNDISP:    DB 7,"display"
SCNNWL:     DB 7,"newline"
SCNWCHR:    DB 10,"write-char"
SCNRDCHR:   DB 9,"read-char"
SCNREAD:    DB 4,"read"
SCNQUOT:    DB 8,"quotient"
SCNREMA:    DB 9,"remainder"
SCNEQNUM:   DB 1,"="
SCNLT:      DB 1,"<"
SCNGT:      DB 1,">"
SCNLE:      DB 2,"<="
SCNGE:      DB 2,">="
SCNNOT:     DB 3,"not"
SCNNUM:     DB 7,"number?"
SCNBOOL:    DB 8,"boolean?"
SCNSYM:     DB 7,"symbol?"
SCNPRO:     DB 10,"procedure?"
SCNSTR:     DB 7,"string?"
SCNCHAR:    DB 5,"char?"
SCNSTRLN:   DB 13,"string-length"
SCNSTRRF:   DB 10,"string-ref"
SCNCHINT:   DB 13,"char->integer"
SCNINTCH:   DB 13,"integer->char"
SCNSTRMK:   DB 6,"string"
SCNSTRCP:   DB 11,"string-copy"
SCNSTRAP:   DB 13,"string-append"
SCNEOFQ:    DB 11,"eof-object?"
SCNVECT:    DB 7,"vector?"
SCNMKV:     DB 11,"make-vector"
SCNVEC:     DB 6,"vector"
SCNVLEN:    DB 13,"vector-length"
SCNVREF:    DB 10,"vector-ref"
SCNVSET:    DB 11,"vector-set!"
SCNAPP:     DB 5,"apply"
SCPORTTB:   DB 18,47,"current-input-port"
            DB 19,48,"current-output-port"
            DB 18,49,"current-error-port"
            DB 5,50,"port?"
            DB 11,51,"input-port?"
            DB 12,52,"output-port?"
            DB 10,53,"close-port"
            DB 15,56,"open-input-file"
            DB 16,57,"open-output-file"
            DB 22,58,"open-input-binary-file"
            DB 23,59,"open-output-binary-file"
