;=============================================================================
;  Scope compiler byte emitter and bounded fixup tables
;=============================================================================
;
;  The parser writes native Z80 bytes into the staged image.  Immediate slot
;  addresses remain zero until the global and local data extents are known.
;  Each fixup is four bytes: staged patch address, slot kind and slot number.
;=============================================================================

; Emit one byte from A and advance the generated-image cursor.
SCBYTE:
        LD HL,(SCPC)              ; Load the next staged output address.
        LD DE,SCGENEND            ; Leave room for the fixed publication tail.
        OR A                      ; Clear carry before comparing the cursor.
        SBC HL,DE                 ; A nonnegative result would overwrite tables.
        JP NC,SCCAP               ; Abort before the first out-of-range write.
        LD HL,(SCPC)              ; Reload the cursor after the bounds check.
        LD (HL),A                 ; Store the instruction or operand byte.
        INC HL                    ; Advance to the next generated byte.
        LD (SCPC),HL              ; Publish the new cursor.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; Return with the caller's byte consumed.

; Emit a little-endian word from HL.
SCWORD:
        LD (SCWTMP),HL            ; Preserve both bytes across SCBYTE calls.
        LD A,(SCWTMP)             ; Emit the low address byte first.
        CALL SCBYTE               ; Append the low byte to the image.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,(SCWTMP+1)           ; Recover the high address byte.
        JP SCBYTE                 ; Append it and return through the emitter.

; Emit CALL address in HL.
SCCALL:
        LD (SCWTMP),HL            ; Preserve the target while writing the opcode.
        LD A,0CDH                 ; Z80 CALL has opcode CDH.
        CALL SCBYTE               ; Append the opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCWTMP)            ; Restore the target word.
        JP SCWORD                 ; Append it and return.

; Emit a literal exact integer in HL.
SCLIT:
        LD (SCVTMP),HL            ; Preserve the literal while writing opcodes.
        LD A,21H                  ; LD HL,nn loads the result payload.
        CALL SCBYTE               ; Append the load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCVTMP)            ; Recover the literal payload.
        CALL SCWORD               ; Append the payload word.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; LD A,3 selects the exact-integer tag.
        CALL SCBYTE               ; Append the tag-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3                    ; The generated value is an exact integer.
        JP SCBYTE                 ; Append the tag and return.

; Emit #f or #t.  A is zero for #f and one for #t.
SCBOOL:
        LD (SCBTMP),A             ; Preserve the logical boolean value.
        LD A,21H                  ; Load the boolean payload into HL.
        CALL SCBYTE               ; Append the payload-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                     ; The boolean payload is a zero-extended byte.
        LD H,A                    ; Clear the payload high byte.
        LD A,(SCBTMP)             ; Recover the selected boolean value.
        LD L,A                    ; Place it in the payload low byte.
        CALL SCWORD               ; Append the payload word.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; Load the scalar tag into A.
        CALL SCBYTE               ; Append the tag-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                     ; Booleans use tag zero.
        JP SCBYTE                 ; Append the tag and return.

; Emit PUSH AF followed by PUSH HL for the value currently in registers.
SCPUSH:
        LD A,0F5H                 ; PUSH AF saves the value tag and flags.
        CALL SCBYTE               ; Append the tag push.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,0E5H                 ; PUSH HL saves the value payload.
        JP SCBYTE                 ; Append the payload push and return.

; Emit a direct load from a compiler-assigned slot.  A=0 selects a global
; slot; A=1 selects a local slot.  L contains the slot number.
SCLOAD:
        LD (SCFKIND),A            ; Keep the slot kind with the pending record.
        LD A,L                    ; Copy the slot number into the pending record.
        LD (SCFSLOT),A            ; A single byte addresses every current slot.
        LD A,21H                  ; LD HL,nn will receive the slot address later.
        CALL SCBYTE               ; Append the load opcode.
        LD HL,(SCPC)              ; The next two bytes are the patch location.
        CALL SCFIX                ; Record them before writing placeholder zeroes.
        RET C                     ; A full fixup table aborts the current form.
        XOR A                     ; Address bytes are filled after layout closes.
        CALL SCBYTE               ; Append the placeholder low byte.
        RET C                     ; Preserve a staged-output capacity failure.
        CALL SCBYTE               ; Append the placeholder high byte.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,SRTLDA         ; Generated code calls the runtime slot loader.
        JP SCCALL                 ; Append the call and return.

; Emit a store to a compiler-assigned slot.  The value remains in A/HL for the
; caller; the generated code moves the destination address into DE first.
SCSTORE:
        LD (SCFKIND),A            ; Keep the slot kind with the pending record.
        LD A,L                    ; Copy the slot number into the pending record.
        LD (SCFSLOT),A            ; A single byte addresses every current slot.
        LD A,11H                  ; LD DE,nn will receive the slot address later.
        CALL SCBYTE               ; Append the store-address opcode.
        LD HL,(SCPC)              ; The next two bytes are the patch location.
        CALL SCFIX                ; Record them before writing placeholder zeroes.
        RET C                     ; A full fixup table aborts the current form.
        XOR A                     ; Address bytes are filled after layout closes.
        CALL SCBYTE               ; Append the placeholder low byte.
        RET C                     ; Preserve a staged-output capacity failure.
        CALL SCBYTE               ; Append the placeholder high byte.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,SRTSTA        ; Generated code calls the runtime slot store.
        JP SCCALL                 ; Append the call and return.

; Record a two-byte staged address, slot kind and slot number.
SCFIX:
        LD (SCFPTR),HL            ; Preserve the patch address while indexing.
        LD HL,(SCFIXN)            ; The table admits the full global fixup target.
        LD DE,320                 ; Leave one guarded region before the tables.
        OR A                      ; Clear carry before the capacity comparison.
        SBC HL,DE                 ; A carry-free result means the table is full.
        JP NC,SCFIXERR            ; Refuse a fixup that would overwrite the table.
        LD HL,(SCFIXN)            ; Recover the record index after the comparison.
        LD DE,SCFIXTAB             ; Locate the next free fixup record.
        ADD HL,HL                 ; Multiply the record index by two.
        ADD HL,HL                 ; Multiply by four for the record width.
        ADD HL,DE                 ; HL points at its staged-address field.
        LD DE,(SCFPTR)            ; Restore the address of the two patch bytes.
        LD (HL),E                 ; Store the patch address low byte.
        INC HL                    ; Advance to the high patch-address byte.
        LD (HL),D                 ; Store the patch address high byte.
        INC HL                    ; Advance to the kind byte.
        LD A,(SCFKIND)            ; Store global or local kind.
        LD (HL),A                 ; Publish the kind before the slot number.
        INC HL                    ; Advance to the slot-number byte.
        LD A,(SCFSLOT)            ; Store the compiler-assigned slot number.
        LD (HL),A                 ; Complete the fixup record.
        LD HL,(SCFIXN)            ; Increment the record count after the write.
        INC HL                    ; The next record uses the following four bytes.
        LD (SCFIXN),HL            ; Publish the complete fixup.
        XOR A                     ; A successful record returns with carry clear.
        RET                       ; Return to the code emitter.

SCFIXERR:
        SCF                       ; The parser reports a bounded fixup failure.
        RET                       ; No staged output is published on this path.

; Emit a conditional absolute jump and return its patch address in HL.  The
; caller patches the address when the matching branch target is known.
SCJZ:
        LD A,0CAH                 ; JP Z,nn branches when SRTFALSE returns Z.
        CALL SCBYTE               ; Append the conditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

SCJNZ:
        LD A,0C2H                 ; JP NZ,nn is the OR short-circuit branch.
        CALL SCBYTE               ; Append the conditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

; Emit JP nn and return its two-byte patch location in HL.
SCJP:
        LD A,0C3H                 ; Absolute Z80 jump opcode.
        CALL SCBYTE               ; Append the unconditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

SCJFAIL:
        POP HL                    ; Remove the saved patch address on failure.
        SCF                       ; Keep the staged-output diagnostic asserted.
        RET

; Append the return instruction used by the runtime entry point.
SCRET:
        LD A,0C9H                 ; RET hands the final value to SRTCALL.
        JP SCBYTE                 ; Append the single-byte instruction.

; Patch a staged branch word at HL with the absolute output address in DE.
SCPATCH:
        EX DE,HL                  ; DE becomes the staged patch address.
        LD (SCPTMP),HL            ; Save the absolute target while writing.
        LD HL,(SCPTMP)            ; Recover the target's low byte in L.
        LD A,L                    ; Copy the target low byte through A.
        LD (DE),A                 ; Patch the low branch-address byte.
        INC DE                    ; Advance to the high branch-address byte.
        LD A,H                    ; Copy the target high byte without flags.
        LD (DE),A                 ; Complete the absolute branch address.
        RET                       ; Return after the two-byte patch.
