; Scope and control compiler assembled for CP/M publication.
%INCLUDE "origin.asm"
%INCLUDE "scope-control-runtime-values.inc"
%INCLUDE "scope-control-command.asm"
%INCLUDE "procedure-forms.asm"
%INCLUDE "scope-control-bindings.asm"
%INCLUDE "scope-control-branches.asm"
%INCLUDE "scope-control-emitter.asm"
%INCLUDE "scope-control-publication.asm"
%INCLUDE "cpm-source.asm"
%INCLUDE "cpm-transport.asm"
%INCLUDE "lexer.asm"
%INCLUDE "decimal.asm"
%INCLUDE "interner.asm"
%INCLUDE "reader.asm"
%INCLUDE "scope-control-runtime-template.inc"
