;=============================================================================
;  Scope compiler byte emitter and bounded fixup tables
;=============================================================================
;
;  The parser writes native Z80 bytes into the staged image.  Immediate slot
;  addresses remain zero until the global and local data extents are known.
;  Each fixup is four bytes: staged patch address, slot kind and slot number.
;=============================================================================

; Emit one byte from A and advance the generated-image cursor.
SCBYTE:
        LD HL,(SCPC)              ; Load the next staged output address.
        LD DE,SCGENEND            ; Leave room for the fixed publication tail.
        OR A                      ; Clear carry before comparing the cursor.
        SBC HL,DE                 ; A nonnegative result would overwrite tables.
        JP NC,SCCAP               ; Abort before the first out-of-range write.
        LD HL,(SCPC)              ; Reload the cursor after the bounds check.
        LD (HL),A                 ; Store the instruction or operand byte.
        INC HL                    ; Advance to the next generated byte.
        LD (SCPC),HL              ; Publish the new cursor.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; Return with the caller's byte consumed.

; Emit a little-endian word from HL.
SCWORD:
        LD (SCWTMP),HL            ; Preserve both bytes across SCBYTE calls.
        LD A,(SCWTMP)             ; Emit the low address byte first.
        CALL SCBYTE               ; Append the low byte to the image.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,(SCWTMP+1)           ; Recover the high address byte.
        JP SCBYTE                 ; Append it and return through the emitter.

; Emit CALL address in HL.
SCCALL:
        LD (SCWTMP),HL            ; Preserve the target while writing the opcode.
        LD A,0CDH                 ; Z80 CALL has opcode CDH.
        CALL SCBYTE               ; Append the opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCWTMP)            ; Restore the target word.
        JP SCWORD                 ; Append it and return.

; Emit a literal exact integer in HL.
SCLIT:
        LD (SCVTMP),HL            ; Preserve the literal while writing opcodes.
        LD A,21H                  ; LD HL,nn loads the result payload.
        CALL SCBYTE               ; Append the load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCVTMP)            ; Recover the literal payload.
        CALL SCWORD               ; Append the payload word.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; LD A,3 selects the exact-integer tag.
        CALL SCBYTE               ; Append the tag-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3                    ; The generated value is an exact integer.
        JP SCBYTE                 ; Append the tag and return.

; Emit an unbound predefined procedure as a reserved immediate value.
; A contains its one-based primitive kind; the runtime subtracts $20 from the
; payload low byte when it selects the dispatcher entry.
SCPRIM:
        LD (SCPKIND),A            ; Preserve the kind while writing the value.
        LD A,21H                  ; LD HL,nn loads the reserved payload.
        CALL SCBYTE
        RET C
        LD A,(SCPKIND)
        DEC A
        ADD A,20H
        CALL SCBYTE                 ; Payload low byte is $20 plus kind minus one.
        RET C
        LD A,0FEH
        CALL SCBYTE                 ; All primitive payloads use the reserved high byte.
        RET C
        LD A,3EH                  ; LD A,n loads the immediate value tag.
        CALL SCBYTE
        RET C
        XOR A                      ; Tag zero identifies a primitive value.
        JP SCBYTE

; Emit and save a predefined procedure on the runtime operator side stack.
SCPRIMV:
        CALL SCPRIM                ; Leave the immediate value in A:HL.
        RET C
        LD HL,SRTOPUSH             ; Preserve it while application arguments compile.
        JP SCCALL

; Emit #f or #t.  A is zero for #f and one for #t.
SCBOOL:
        LD (SCBTMP),A             ; Preserve the logical boolean value.
        LD A,21H                  ; Load the boolean payload into HL.
        CALL SCBYTE               ; Append the payload-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                     ; The boolean payload is a zero-extended byte.
        LD H,A                    ; Clear the payload high byte.
        LD A,(SCBTMP)             ; Recover the selected boolean value.
        LD L,A                    ; Place it in the payload low byte.
        CALL SCWORD               ; Append the payload word.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; Load the scalar tag into A.
        CALL SCBYTE               ; Append the tag-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                     ; Booleans use tag zero.
        JP SCBYTE                 ; Append the tag and return.

; Emit a byte character.  Characters share the scalar tag with booleans, but
; keep the FFxx payload so predicates can distinguish them from numbers.
SCCHAR:
        LD (SCVTMP),HL            ; Preserve the complete FFxx payload.
        LD A,21H                  ; Load the character payload into HL.
        CALL SCBYTE               ; Append the payload-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCVTMP)            ; Recover the character payload.
        CALL SCWORD               ; Append both payload bytes unchanged.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; Load the scalar tag into A.
        CALL SCBYTE               ; Append the tag-load opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                     ; Characters use the established scalar tag.
        JP SCBYTE                 ; Append the tag and return.

; Emit the canonical unspecified value (tag zero, payload FE04H).
SCUNS:
        LD A,21H                  ; Load the reserved immediate payload.
        CALL SCBYTE               ; Append the LD HL,nn opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,0FE04H              ; FE04H is the language's UNSPECIFIED value.
        CALL SCWORD                ; Append the payload in little-endian order.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,3EH                  ; Load the tag register with zero.
        CALL SCBYTE               ; Append the LD A,n opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        XOR A                      ; Tag zero identifies immediate values.
        JP SCBYTE                  ; Append the tag and return.

; Emit PUSH AF followed by PUSH HL for the value currently in registers.
SCPUSH:
        LD A,0F5H                 ; PUSH AF saves the value tag and flags.
        CALL SCBYTE               ; Append the tag push.
        RET C                     ; Preserve a staged-output capacity failure.
        LD A,0E5H                 ; PUSH HL saves the value payload.
        JP SCBYTE                 ; Append the payload push and return.

; Recover a value saved by SCPUSH.  The payload was pushed after its tag.
SCPOP:
        LD A,0E1H                 ; POP HL restores the payload first.
        CALL SCBYTE               ; Append the payload pop.
        RET C                     ; Preserve staged-output exhaustion.
        LD A,0F1H                 ; POP AF restores the scalar tag and flags.
        JP SCBYTE                 ; Append the tag pop and return.

; Emit a clear of a recursive cell before its first initializer runs.
SCCLEAR:
        LD A,L
        LD (SCFSLOT),A
        LD A,1
        CALL SCLOCALQ
        JR Z,SCCLRS
        LD A,06H
        CALL SCBYTE
        RET C
        LD A,(SCFSLOT)
        CALL SCBYTE
        RET C
        LD HL,SRTCLRI
        JP SCCALL
SCCLRS:
        LD A,21H
        CALL SCBYTE
        RET C
        LD HL,(SCPC)
        LD A,1
        LD (SCFKIND),A
        LD A,(SCFSLOT)
        CALL SCFIX
        RET C
        XOR A
        CALL SCBYTE
        RET C
        CALL SCBYTE
        RET C
        LD HL,SRTCLRS
        JP SCCALL

; Emit a direct load from a compiler-assigned slot.  A=0 selects a global
; slot; A=1 selects a local slot.  L contains the slot number.
SCLOAD:
        LD (SCFKIND),A            ; Keep the slot kind with the pending record.
        LD A,L                    ; Copy the slot number into the pending record.
        LD (SCFSLOT),A            ; A single byte addresses every current slot.
        LD A,(SCFKIND)
        CP 1
        JR NZ,SCLDFIX               ; Globals and top-level lets retain static slots.
        CALL SCLOCALQ              ; Package-owned locals remain static.
        JR Z,SCLDFIX
        LD A,3EH                   ; LD A,slot supplies the dynamic slot index.
        CALL SCBYTE
        RET C
        LD A,(SCFSLOT)
        CALL SCBYTE
        RET C
        LD HL,SRTLOADI             ; Load through the active environment map.
        JP SCCALL
SCLDFIX:
        LD A,21H                  ; LD HL,nn will receive the slot address later.
        CALL SCBYTE               ; Append the load opcode.
        LD HL,(SCPC)              ; The next two bytes are the patch location.
        CALL SCFIX                ; Record them before writing placeholder zeroes.
        RET C                     ; A full fixup table aborts the current form.
        XOR A                     ; Address bytes are filled after layout closes.
        CALL SCBYTE               ; Append the placeholder low byte.
        RET C                     ; Preserve a staged-output capacity failure.
        CALL SCBYTE               ; Append the placeholder high byte.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,SRTLDA         ; Generated code calls the runtime slot loader.
        JP SCCALL                 ; Append the call and return.

; Emit a store to a compiler-assigned slot.  The value remains in A/HL for the
; caller; the generated code moves the destination address into DE first.
SCSTORE:
        LD (SCFKIND),A            ; Keep the slot kind with the pending record.
        LD A,L                    ; Copy the slot number into the pending record.
        LD (SCFSLOT),A            ; A single byte addresses every current slot.
        LD A,(SCFKIND)             ; Procedure locals use the active environment.
        CP 1
        JR NZ,SCSTFIX               ; Globals and top-level lets retain static slots.
        LD A,(SCCURPR)
        CALL SCLOCALQ              ; Package-owned locals remain static.
        JR Z,SCSTFIX
        LD A,06H                   ; LD B,slot supplies the dynamic slot index.
        CALL SCBYTE
        RET C
        LD A,(SCFSLOT)
        CALL SCBYTE
        RET C
        LD HL,SRTSTORI             ; Store through the active environment map.
        LD A,(SCMUT)           ; Mutation selects the checked local helper.
        OR A
        JR Z,SCSTLOC              ; Definitions use the initializing helper.
        LD HL,SRTSETI
SCSTLOC:
        JP SCCALL
SCSTFIX:
        LD A,11H                  ; LD DE,nn will receive the slot address later.
        CALL SCBYTE               ; Append the store-address opcode.
        LD HL,(SCPC)              ; The next two bytes are the patch location.
        CALL SCFIX                ; Record them before writing placeholder zeroes.
        RET C                     ; A full fixup table aborts the current form.
        XOR A                     ; Address bytes are filled after layout closes.
        CALL SCBYTE               ; Append the placeholder low byte.
        RET C                     ; Preserve a staged-output capacity failure.
        CALL SCBYTE               ; Append the placeholder high byte.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,SRTSTA                ; Generated code calls the runtime slot store.
        LD A,(SCMUT)            ; Mutation selects the checked static helper.
        OR A
        JR Z,SCSTSTAT              ; Definitions initialize the destination.
        LD HL,SRTSETS
SCSTSTAT:
        JP SCCALL                 ; Append the call and return.

; Save the value of a predefined global procedure before its arguments run.
; The side stack preserves Scheme's operator-first evaluation order without
; placing a callee word on the native stack for every recursive call.
SCGMARK:
        LD A,21H                  ; LD HL,nn receives the global cell address.
        CALL SCBYTE
        RET C
        LD HL,(SCPC)              ; The following word is fixed after layout.
        LD A,0                    ; Fixup kind zero selects global storage.
        LD (SCFKIND),A
        LD A,(SCAPGSL)            ; The marker carries the selected global slot.
        LD (SCFSLOT),A
        CALL SCFIX
        RET C
        XOR A                     ; Leave both address bytes as placeholders.
        CALL SCBYTE
        RET C
        CALL SCBYTE
        RET C
        LD HL,SRTLDA              ; Read the value while the operator is current.
        CALL SCCALL
        RET C
        LD HL,SRTOPUSH            ; Preserve the four-byte value across arguments.
        JP SCCALL

; Record a two-byte staged address, slot kind and slot number.
SCFIX:
        LD (SCFPTR),HL            ; Preserve the patch address while indexing.
        LD HL,(SCFIXN)            ; The table admits the full global fixup target.
        LD DE,320                 ; Leave one guarded region before the tables.
        OR A                      ; Clear carry before the capacity comparison.
        SBC HL,DE                 ; A carry-free result means the table is full.
        JP NC,SCFIXERR            ; Refuse a fixup that would overwrite the table.
        LD HL,(SCFIXN)            ; Recover the record index after the comparison.
        LD DE,SCFIXTAB             ; Locate the next free fixup record.
        ADD HL,HL                 ; Multiply the record index by two.
        ADD HL,HL                 ; Multiply by four for the record width.
        ADD HL,DE                 ; HL points at its staged-address field.
        LD DE,(SCFPTR)            ; Restore the address of the two patch bytes.
        LD (HL),E                 ; Store the patch address low byte.
        INC HL                    ; Advance to the high patch-address byte.
        LD (HL),D                 ; Store the patch address high byte.
        INC HL                    ; Advance to the kind byte.
        LD A,(SCFKIND)            ; Store global or local kind.
        LD (HL),A                 ; Publish the kind before the slot number.
        INC HL                    ; Advance to the slot-number byte.
        LD A,(SCFSLOT)            ; Store the compiler-assigned slot number.
        LD (HL),A                 ; Complete the fixup record.
        LD HL,(SCFIXN)            ; Increment the record count after the write.
        INC HL                    ; The next record uses the following four bytes.
        LD (SCFIXN),HL            ; Publish the complete fixup.
        XOR A                     ; A successful record returns with carry clear.
        RET                       ; Return to the code emitter.

SCFIXERR:
        SCF                       ; The parser reports a bounded fixup failure.
        RET                       ; No staged output is published on this path.

; Record the staged operand word of a tail-call wrapper for later rewriting.
SCTSAVE:
        LD (SCTPTR),HL             ; Preserve the operand address during indexing.
        LD A,(SCTTOP)              ; Each record occupies one staged address word.
        CP SCTMAX                  ; Refuse a body that exceeds the patch bound.
        JP NC,SCCAP                ; A partial tail record cannot be emitted safely.
        LD L,A                     ; Widen the record index before doubling it.
        LD H,0
        ADD HL,HL
        LD DE,SCTAILPT             ; Locate the next free tail-candidate record.
        ADD HL,DE
        LD DE,(SCTPTR)             ; Restore the staged operand address.
        LD (HL),E                  ; Store its low byte.
        INC HL
        LD (HL),D                  ; Store its high byte.
        LD L,A                     ; Reuse the candidate index for its side flag.
        LD H,0
        LD DE,SCTAILK
        ADD HL,DE
        LD A,(SCAPMODE)            ; Mode two means the operator uses the side stack.
        CP 2
        JR NZ,SCTSAVEG
        LD A,1
SCTSAVEG:
        LD (HL),A                  ; Preserve the dispatch path for later rewriting.
        LD A,(SCTTOP)              ; Advance the candidate count after the write.
        INC A
        LD (SCTTOP),A
        XOR A
        RET

; Rewrite the current body's non-final tail candidates as ordinary calls.
SCTFIX:
        LD A,(SCTMARK)             ; The current expression owns records from here.
        LD B,A                     ; B walks the bounded patch-record range.
SCTFIXLP:
        LD A,(SCTTOP)              ; Stop when every candidate in this expression is fixed.
        CP B
        JR Z,SCTFIXDN
        LD L,B                     ; Address the candidate word by its record index.
        LD H,0
        ADD HL,HL
        LD DE,SCTAILPT
        ADD HL,DE
        LD E,(HL)                  ; Recover the staged operand address.
        INC HL
        LD D,(HL)
        EX DE,HL                   ; HL now names the generated CALL operand.
        PUSH HL                    ; Preserve the patch address while reading its flag.
        LD L,B                     ; The flag table uses one byte per candidate.
        LD H,0
        LD DE,SCTAILK
        ADD HL,DE
        LD A,(HL)                  ; A nonzero flag selects the side-stack entry.
        POP HL                     ; Restore the staged operand address.
        OR A
        JR Z,SCTFIXG
        LD DE,SRTOPINV             ; Keep operator-first evaluation for this call.
        JR SCTFIXW
SCTFIXG:
        LD DE,SRTINVOK             ; Ordinary calls preserve the continuation.
SCTFIXW:
        LD (HL),E
        INC HL
        LD (HL),D
        INC B                      ; Advance to the next tail candidate.
        JR SCTFIXLP
SCTFIXDN:
        LD A,B                     ; Discard the records just rewritten.
        LD (SCTTOP),A
        XOR A
        RET

; Return Z when the selected local slot belongs to package-level storage.
SCLOCALQ:
        LD A,(SCFSLOT)             ; Address the owner byte for the selected slot.
        LD L,A
        LD H,0
        LD DE,SCLOCOWN
        ADD HL,DE
        LD A,(HL)
        CP 0FFH
        RET

; Emit a conditional absolute jump and return its patch address in HL.  The
; caller patches the address when the matching branch target is known.
SCJZ:
        LD A,0CAH                 ; JP Z,nn branches when SRTFALSE returns Z.
        CALL SCBYTE               ; Append the conditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

SCJNZ:
        LD A,0C2H                 ; JP NZ,nn is the OR short-circuit branch.
        CALL SCBYTE               ; Append the conditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

; Emit JP nn and return its two-byte patch location in HL.
SCJP:
        LD A,0C3H                 ; Absolute Z80 jump opcode.
        CALL SCBYTE               ; Append the unconditional-jump opcode.
        RET C                     ; Preserve a staged-output capacity failure.
        LD HL,(SCPC)              ; The following word is the branch patch.
        PUSH HL                   ; Preserve the patch address across zero writes.
        XOR A                     ; Start with an unresolved target word.
        CALL SCBYTE               ; Append the low placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        CALL SCBYTE               ; Append the high placeholder byte.
        JR C,SCJFAIL              ; Leave the patch address off the stack.
        POP HL                    ; Return the branch patch location.
        OR A                      ; Successful emission returns carry clear.
        RET                       ; The caller owns the patch stack.

SCJFAIL:
        POP HL                    ; Remove the saved patch address on failure.
        SCF                       ; Keep the staged-output diagnostic asserted.
        RET

; Append the return instruction used by the runtime entry point.
SCRET:
        LD A,0C9H                 ; RET hands the final value to SRTCALL.
        JP SCBYTE                 ; Append the single-byte instruction.

; Patch a staged branch word at HL with the absolute output address in DE.
SCPATCH:
        EX DE,HL                  ; DE becomes the staged patch address.
        LD (SCPTMP),HL            ; Save the absolute target while writing.
        LD HL,(SCPTMP)            ; Recover the target's low byte in L.
        LD A,L                    ; Copy the target low byte through A.
        LD (DE),A                 ; Patch the low branch-address byte.
        INC DE                    ; Advance to the high branch-address byte.
        LD A,H                    ; Copy the target high byte without flags.
        LD (DE),A                 ; Complete the absolute branch address.
        RET                       ; Return after the two-byte patch.
