; Scope-control runtime image assembled at the CP/M load origin.
%INCLUDE "scope-control-runtime.asm"
%INCLUDE "scope-control-runtime-managed.asm"
%INCLUDE "scope-control-page.asm"
%INCLUDE "scope-control-runtime-primitives.asm"
%INCLUDE "scope-control-pair-management.asm"
%INCLUDE "scope-control-pairs.asm"
%INCLUDE "scope-control-runtime-roots.asm"
%INCLUDE "scope-control-runtime-data.asm"
%INCLUDE "scope-control-runtime-float.asm"
%INCLUDE "scope-control-runtime-output.asm"
%INCLUDE "scope-control-runtime-managed-slabs.asm"
%INCLUDE "../../runtime/binary16.asm"
%INCLUDE "../../runtime/numeric.asm"
