; Generated-byte and fixup sink used by the compiler.
;
; ST_PC is a logical COM address. The sink keeps at most one canonical 128-byte
; IMAGE run in W_IMAGE and writes completed ASO records through CPM_PUT. A PATCH
; flushes that run first, preserving the order of generated bytes and fixups.

; Emit one generated byte from A at the current logical COM address.
SINK_PUT:
.ALIAS:
        PUSH BC                    ; Existing emitters keep loop counts in BC.
        LD (ASO_BYTE),A            ; Keep the byte while checking the cursor.
        LD A,(ST_PCHI)             ; The top byte marks the exclusive $10000 end.
        OR A
        JR NZ,.FULL                ; No byte may be emitted after the address space.
        LD A,(ASO_CNT)             ; An empty run needs a new logical start.
        OR A
        JR Z,.NEW_RUN
        LD HL,(ST_PC)              ; Recover the unchanged logical cursor.
        LD DE,(ASO_END)            ; A matching end extends the pending IMAGE run.
        OR A                       ; Clear carry before comparing the endpoints.
        SBC HL,DE
        JR Z,.APPEND               ; The byte is adjacent to the current run.
.NEW_RUN:
        CALL ASO_EMIT               ; A gap or prior PATCH starts a fresh run.
        JR C,.FAIL                 ; Preserve a failed ASO transport operation.
        LD HL,(ST_PC)              ; Start the new run at the current address.
        LD (ASO_RUN),HL            ; Retain its logical ASO address.
.APPEND:
        LD A,(ASO_CNT)             ; Select the next byte in the bounded run buffer.
        LD E,A
        LD D,0
        LD HL,W_IMAGE
        ADD HL,DE
        LD A,(ASO_BYTE)             ; Recover the generated byte.
        LD (HL),A                  ; Buffer it until a record boundary or PATCH.
        LD HL,(ST_PC)
        LD A,H
        CP 0FFH
        JR NZ,.ADVANCE
        LD A,L
        CP 0FFH
        JR NZ,.ADVANCE
        LD A,(ST_PCHI)
        INC A                       ; The only permitted wrap reaches $10000.
        LD (ST_PCHI),A
.ADVANCE:
        INC HL                     ; The exclusive high-water address advances.
        LD (ST_PC),HL
        LD (ASO_END),HL
        LD (ASO_HIGH),HL           ; Keep the greatest IMAGE endpoint for PATCH.
        LD A,(ST_PCHI)
        LD (ASO_TOP),A             ; Keep the ASO high-water top byte in step.
        LD HL,ASO_CNT
        INC (HL)                   ; Canonical IMAGE records contain at most 128 bytes.
        LD A,(ASO_CNT)
        CP 128
        JR NZ,.DONE                ; Keep a short run in RAM.
        CALL ASO_EMIT              ; Flush a full record immediately.
        JR C,.FAIL
.DONE:
        LD A,(ASO_BYTE)            ; Preserve the emitted byte for zero-fill loops.
        POP BC
        OR A
        RET
.FULL:
        POP BC
        JP ERR_CAP
.FAIL:
        POP BC
        JP ASO_FAIL

; Emit a two-byte PATCH at logical address HL with the absolute target in DE.
SINK_FIX:
.ALIAS:
        PUSH BC                    ; Fixup callers may be inside counted loops.
        LD (ST_FADDR),HL           ; Retain the patch address across the flush.
        LD (PUB_ABS),DE            ; Retain the replacement word as well.
        CALL ASO_EMIT              ; PATCH records are barriers between IMAGE runs.
        JR C,.FAIL               ; Do not write a partial PATCH after a failure.
        LD HL,(ST_FADDR)           ; The patch must be within emitted IMAGE bytes.
        LD DE,0100H
        OR A
        SBC HL,DE
        JR C,.FULL
        LD HL,(ST_FADDR)
        LD DE,2
        ADD HL,DE
        JR NC,.NO_WRAP
        LD A,H
        OR L
        JR NZ,.FULL                ; Only $FFFE + 2 reaches the exact endpoint.
        LD A,1
        LD (SINK_TOP),A
        JR .CHECK
.NO_WRAP:
        XOR A
        LD (SINK_TOP),A
.CHECK:
        LD A,(ASO_TOP)
        OR A
        JR NZ,.WRITE               ; Every nonwrapped patch fits below $10000.
        LD A,(SINK_TOP)
        OR A
        JR NZ,.FULL                ; A wrapped patch exceeds a short image.
        LD DE,(ASO_HIGH)
        OR A
        SBC HL,DE
        JR C,.WRITE
        JR Z,.WRITE
        JP .FULL
.WRITE:
        LD A,2                     ; ASO record kind two denotes PATCH.
        CALL CPM_PUT
        JR C,.FAIL
        LD HL,(ST_FADDR)
        CALL ASO_WORD              ; Write the logical patch address.
        JR C,.FAIL
        LD A,2                     ; Both compiler fixups replace two bytes.
        CALL CPM_PUT
        JR C,.FAIL
        LD HL,(PUB_ABS)
        CALL ASO_WORD              ; Write the little-endian replacement word.
        JR C,.FAIL
        XOR A
        POP BC
        RET
.FULL:
        POP BC
        JP ERR_CAP
.FAIL:
        POP BC
        JP ASO_FAIL
