; Generated-byte and fixup sink used by the compiler.
;
; ST_PC is a logical COM address. The sink keeps at most one canonical 128-byte
; IMAGE run in W_IMAGE and writes completed ASO records through CPM_PUT. A PATCH
; flushes that run first, preserving the order of generated bytes and fixups.

; Emit one generated byte from A at the current logical COM address.
SINKBYTE:
SCBYTE:
        PUSH BC                    ; Existing emitters keep loop counts in BC.
        LD (SCABYTE),A             ; Keep the byte while checking the cursor.
        LD A,(ST_PCHI)             ; The top byte marks the exclusive $10000 end.
        OR A
        JR NZ,SINKCAP              ; No byte may be emitted after the address space.
        LD A,(SCARUNC)             ; An empty run needs a new logical start.
        OR A
        JR Z,SINKNEW
        LD HL,(ST_PC)              ; Recover the unchanged logical cursor.
        LD DE,(SCAREND)            ; A matching end extends the pending IMAGE run.
        OR A                       ; Clear carry before comparing the endpoints.
        SBC HL,DE
        JR Z,SINKAPP               ; The byte is adjacent to the current run.
SINKNEW:
        CALL SCARUNFL               ; A gap or prior PATCH starts a fresh run.
        JR C,SINKFAIL              ; Preserve a failed ASO transport operation.
        LD HL,(ST_PC)              ; Start the new run at the current address.
        LD (SCARADD),HL            ; Retain its logical ASO address.
SINKAPP:
        LD A,(SCARUNC)             ; Select the next byte in the bounded run buffer.
        LD E,A
        LD D,0
        LD HL,W_IMAGE
        ADD HL,DE
        LD A,(SCABYTE)              ; Recover the generated byte.
        LD (HL),A                  ; Buffer it until a record boundary or PATCH.
        LD HL,(ST_PC)
        LD A,H
        CP 0FFH
        JR NZ,SINKCUR
        LD A,L
        CP 0FFH
        JR NZ,SINKCUR
        LD A,(ST_PCHI)
        INC A                       ; The only permitted wrap reaches $10000.
        LD (ST_PCHI),A
SINKCUR:
        INC HL                     ; The exclusive high-water address advances.
        LD (ST_PC),HL
        LD (SCAREND),HL
        LD (SCAHIGH),HL            ; Keep the greatest IMAGE endpoint for PATCH.
        LD A,(ST_PCHI)
        LD (SCAETOP),A             ; Keep the ASO high-water top byte in step.
        LD HL,SCARUNC
        INC (HL)                   ; Canonical IMAGE records contain at most 128 bytes.
        LD A,(SCARUNC)
        CP 128
        JR NZ,SINKOK               ; Keep a short run in RAM.
        CALL SCARUNFL              ; Flush a full record immediately.
        JR C,SINKFAIL
SINKOK:
        LD A,(SCABYTE)             ; Preserve the emitted byte for zero-fill loops.
        POP BC
        OR A
        RET
SINKCAP:
        POP BC
        JP ERR_CAP
SINKFAIL:
        POP BC
        JP SCAERR

; Emit a two-byte PATCH at logical address HL with the absolute target in DE.
SINKPTCH:
SCPATCH:
        PUSH BC                    ; Fixup callers may be inside counted loops.
        LD (ST_FADDR),HL           ; Retain the patch address across the flush.
        LD (SCTARG),DE             ; Retain the replacement word as well.
        CALL SCARUNFL              ; PATCH records are barriers between IMAGE runs.
        JR C,SINKPFL             ; Do not write a partial PATCH after a failure.
        LD HL,(ST_FADDR)           ; The patch must be within emitted IMAGE bytes.
        LD DE,0100H
        OR A
        SBC HL,DE
        JR C,SINKPCAP
        LD HL,(ST_FADDR)
        LD DE,2
        ADD HL,DE
        JR NC,SINKPEND
        LD A,H
        OR L
        JR NZ,SINKPCAP             ; Only $FFFE + 2 reaches the exact endpoint.
        LD A,1
        LD (SCFPET),A
        JR SINKPCMP
SINKPEND:
        XOR A
        LD (SCFPET),A
SINKPCMP:
        LD A,(SCAETOP)
        OR A
        JR NZ,SINKPWR              ; Every nonwrapped patch fits below $10000.
        LD A,(SCFPET)
        OR A
        JR NZ,SINKPCAP             ; A wrapped patch exceeds a short image.
        LD DE,(SCAHIGH)
        OR A
        SBC HL,DE
        JR C,SINKPWR
        JR Z,SINKPWR
        JP SINKPCAP
SINKPWR:
        LD A,2                     ; ASO record kind two denotes PATCH.
        CALL CPM_PUT
        JR C,SINKPFL
        LD HL,(ST_FADDR)
        CALL SCAWORD               ; Write the logical patch address.
        JR C,SINKPFL
        LD A,2                     ; Both compiler fixups replace two bytes.
        CALL CPM_PUT
        JR C,SINKPFL
        LD HL,(SCTARG)
        CALL SCAWORD               ; Write the little-endian replacement word.
        JR C,SINKPFL
        XOR A
        POP BC
        RET
SINKPCAP:
        POP BC
        JP ERR_CAP
SINKPFL:
        POP BC
        JP SCAERR
